# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oppo/PDEM30/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oppo/PDEM30

PRODUCT_COPY_FILES += \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/alipay.b00:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/alipay.b00 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/alipay.b01:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/alipay.b01 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/alipay.b02:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/alipay.b02 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/alipay.b03:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/alipay.b03 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/alipay.b04:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/alipay.b04 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/alipay.b05:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/alipay.b05 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/alipay.b06:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/alipay.b06 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/alipay.b07:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/alipay.b07 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/alipay.mdt:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/alipay.mdt \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/cryptoeng.b00:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/cryptoeng.b00 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/cryptoeng.b01:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/cryptoeng.b01 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/cryptoeng.b02:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/cryptoeng.b02 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/cryptoeng.b03:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/cryptoeng.b03 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/cryptoeng.b04:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/cryptoeng.b04 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/cryptoeng.b05:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/cryptoeng.b05 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/cryptoeng.b06:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/cryptoeng.b06 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/cryptoeng.b07:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/cryptoeng.b07 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/cryptoeng.mdt:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/cryptoeng.mdt \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/dxhdcp2.b00:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/dxhdcp2.b00 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/dxhdcp2.b01:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/dxhdcp2.b01 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/dxhdcp2.b02:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/dxhdcp2.b02 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/dxhdcp2.b03:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/dxhdcp2.b03 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/dxhdcp2.b04:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/dxhdcp2.b04 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/dxhdcp2.b05:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/dxhdcp2.b05 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/dxhdcp2.b06:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/dxhdcp2.b06 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/dxhdcp2.b07:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/dxhdcp2.b07 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/dxhdcp2.mdt:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/dxhdcp2.mdt \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/facereg.b00:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/facereg.b00 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/facereg.b01:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/facereg.b01 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/facereg.b02:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/facereg.b02 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/facereg.b03:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/facereg.b03 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/facereg.b04:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/facereg.b04 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/facereg.b05:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/facereg.b05 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/facereg.b06:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/facereg.b06 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/facereg.b07:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/facereg.b07 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/facereg.mdt:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/facereg.mdt \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/goodixfp.b00:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/goodixfp.b00 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/goodixfp.b01:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/goodixfp.b01 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/goodixfp.b02:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/goodixfp.b02 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/goodixfp.b03:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/goodixfp.b03 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/goodixfp.b04:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/goodixfp.b04 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/goodixfp.b05:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/goodixfp.b05 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/goodixfp.b06:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/goodixfp.b06 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/goodixfp.b07:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/goodixfp.b07 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/goodixfp.mdt:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/goodixfp.mdt \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/hdcpsrm.b00:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/hdcpsrm.b00 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/hdcpsrm.b01:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/hdcpsrm.b01 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/hdcpsrm.b02:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/hdcpsrm.b02 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/hdcpsrm.b03:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/hdcpsrm.b03 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/hdcpsrm.b04:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/hdcpsrm.b04 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/hdcpsrm.b05:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/hdcpsrm.b05 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/hdcpsrm.b06:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/hdcpsrm.b06 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/hdcpsrm.b07:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/hdcpsrm.b07 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/hdcpsrm.mdt:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/hdcpsrm.mdt \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/teemodel:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/teemodel \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/widevine.b00:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/widevine.b00 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/widevine.b01:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/widevine.b01 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/widevine.b02:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/widevine.b02 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/widevine.b03:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/widevine.b03 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/widevine.b04:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/widevine.b04 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/widevine.b05:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/widevine.b05 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/widevine.b06:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/widevine.b06 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/widevine.b07:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/widevine.b07 \
    vendor/oppo/PDEM30/proprietary/my_odm/vendor/firmware/widevine.mdt:$(TARGET_COPY_OUT_SYSTEM)/my_odm/vendor/firmware/widevine.mdt \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/etc/oppo_app_scale_list.xml:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/etc/oppo_app_scale_list.xml \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/etc/oppo_display_perf_list.xml:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/etc/oppo_display_perf_list.xml \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/etc/oppo_rc_bottom.png:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/etc/oppo_rc_bottom.png \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/etc/oppo_rc_left.png:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/etc/oppo_rc_left.png \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/etc/oppo_rc_right.png:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/etc/oppo_rc_right.png \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/etc/oppo_rc_top.png:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/etc/oppo_rc_top.png \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/firmware/alipay.b00:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/firmware/alipay.b00 \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/firmware/alipay.b01:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/firmware/alipay.b01 \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/firmware/alipay.b02:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/firmware/alipay.b02 \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/firmware/alipay.b03:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/firmware/alipay.b03 \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/firmware/alipay.b04:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/firmware/alipay.b04 \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/firmware/alipay.b05:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/firmware/alipay.b05 \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/firmware/alipay.b06:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/firmware/alipay.b06 \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/firmware/alipay.b07:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/firmware/alipay.b07 \
    vendor/oppo/PDEM30/proprietary/my_product/vendor/firmware/alipay.mdt:$(TARGET_COPY_OUT_SYSTEM)/my_product/vendor/firmware/alipay.mdt \
    vendor/oppo/PDEM30/proprietary/product/etc/permissions/vendor.qti.hardware.data.connection-V1.0-java.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/vendor.qti.hardware.data.connection-V1.0-java.xml \
    vendor/oppo/PDEM30/proprietary/product/etc/permissions/vendor.qti.hardware.data.connection-V1.1-java.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/vendor.qti.hardware.data.connection-V1.1-java.xml
